### PR TITLE
Add Oxanas makeNegative func and the test

### PR DESCRIPTION
**Pull request by oxangyal**

### CODE REVIEW

**Review by TimothyHuxx — CHANGES_REQUESTED** [review]
please change your test file name to the following nameOfYourFunc_Func_YourName.spec.js

**Review by LIliia149 — APPROVED** [review]
good

**Review by LIliia149 — COMMENTED** [review]
please change the name

**Review by LIliia149 — DISMISSED** [review]
Oxana, please do not forget your file to be named 'nameOfYourFunc_Func_YourName.spec.js' (.spec.js) :)

**Comment by oxangyal** [comment]
> please change your test file name to the following nameOfYourFunc_Func_YourName.spec.js

Done
Thanx!

**Comment by oxangyal** [comment]
> please change the name

done! thanx!

**Review by TimothyHuxx — APPROVED** [review]
Approved

**Review by IrynaVaku — COMMENTED** [review]
Good job!

**Review by derearte — APPROVED** [review]
Approved

**Pull request merged**
