### PR TITLE
Vik oct 24

### PR DESCRIPTION
**Pull request by Vik1975**
New comment added

### CODE REVIEW

**Review by TimothyHuxx — CHANGES_REQUESTED** [review]
It's my fault that I missed it in your previous PR but let's remember the task again. 
1. Name your files appropriately for tests  nameOfYourFunct_thenIncludeTheWordFunc_YourName.js
Simmer for src file NameOfTheFunc_WordFuc_yourName.js
2.No unnecessary comments (keep your files clean)

**Comment by Vik1975** [comment]
Got it. Thank you Tim

**Comment by Vik1975** [comment]
done

**Review by TimothyHuxx — CHANGES_REQUESTED** [review]
-Please remove unnecessary comments and logs from your test. (console.debug & comments)
-in the name of your test file add " _ "before your name
- suggestion for your test case. The way you wrote it goes as one test case with the test data as an array. In other words, it is one test. If your intention was to make multiple test cases using for loop you should consider moving your for loop before "it".

**Review by AnnaIurchyk — CHANGES_REQUESTED** [review]
Please delete console debug
Change file name

**Review by AnnaIurchyk — APPROVED** [review]
Approved

**Review by TimothyHuxx — APPROVED** [review]
Approved

**Pull request merged**
