### PR TITLE
Vik oct 24

### PR DESCRIPTION
**Pull request by Vik1975**
Delete duplicates

### CODE REVIEW

**Review by adiuzhikov — DISMISSED** [review]
1. Correct the source in test file;
2. Correct the word polyndrom/palyndrom everywhere - it's palindrome;
3. I'm not sure the test is doing what it's supposed to do (checking for palindrome) - it's just comparing each element of the the array with itself.

**Review by TimothyHuxx — CHANGES_REQUESTED** [review]
-Please change "polyndrome" to "palindrome" everywhere in your files.
-In your test keep line 3 (empty line)

**Comment by Vik1975** [comment]
> 1. Correct the source in test file;
> 2. Correct the word polyndrom/palyndrom everywhere - it's palindrome;
> 3. I'm not sure the test is doing what it's supposed to do (checking for palindrome) - it's just comparing each element of the the array with itself.

3. It is comparing the original element in array with the reversed one to make sure it is palindrome.

**Comment by adiuzhikov** [comment]
> > 1. Correct the source in test file;
> > 2. Correct the word polyndrom/palyndrom everywhere - it's palindrome;
> > 3. I'm not sure the test is doing what it's supposed to do (checking for palindrome) - it's just comparing each element of the the array with itself.
> 
> 3. It is comparing the original element in array with the reversed one to make sure it is palindrome.

I can't see where you reversed any of the elements of the array:
expect(palindrome(**test_data[i]**)).to.be.equal(**test_data[i]**)

**Review by TimothyHuxx — CHANGES_REQUESTED** [review]
in your test please add an empty line between your imports and describe (line 3 should be empty)

**Comment by Vik1975** [comment]
See palindrom_func.src. Функция переворачивает слово

**Review by yuliaLopa — APPROVED** [review]
Good

**Review by TimothyHuxx — APPROVED** [review]
approved

**Pull request merged**
