### PR TITLE
New file with a function + test cases

### PR DESCRIPTION
**Pull request by adiuzhikov**
Added a new file with a function + a new file with test cases:

twoDecimalPlaces - Each floating-point number should be formatted that only the first two decimal places are returned.

### CODE REVIEW

**Review by TimothyHuxx — APPROVED** [review]
Great job. Approved

**Comment by yuliaLopa** [comment]
aproved

**Review by yuliaLopa — APPROVED** [review]
aproved

**Review by Sviatlana29 — APPROVED** [review]
Great job!

**Review by shabaiev — APPROVED** [review]
niiiiice

**Pull request merged**
